version: "3"

services:

  migrate:
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: DockerfileMigrate
    container_name: migrate-news-db
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/secrets/adc.json
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      # Replace with your host machine's actual path
      - ~/.config/gcloud/application_default_credentials.json:/app/secrets/adc.json:ro

  news-api:
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: DockerfileAPI
    container_name: news-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
      - migrate
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: news-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psql
      POSTGRES_DB: news_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
